
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

export class GeminiService {
  private static getClient() {
    return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  static async generateMockup(logoBase64: string, prompt: string): Promise<string> {
    const ai = this.getClient();
    
    // Clean the base64 string if it contains the data prefix
    const base64Data = logoBase64.split(',')[1] || logoBase64;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png'
            }
          },
          {
            text: `ACT AS A PROFESSIONAL PRODUCT PHOTOGRAPHER AND MERCH DESIGNER. ${prompt}`
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error('No image was generated by the model.');
  }

  static async editMockup(currentImageBase64: string, editPrompt: string): Promise<string> {
    const ai = this.getClient();
    const base64Data = currentImageBase64.split(',')[1] || currentImageBase64;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png'
            }
          },
          {
            text: `Use this product mockup as a base and modify it based on this request: "${editPrompt}". Keep the product and logo placement intact but change the environment, lighting, or style as requested.`
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error('No edited image was generated.');
  }
}
